#!/bin/bash

# This script shows the files that need to be added to Xcode
echo "============================================"
echo "FILES TO ADD TO XCODE PROJECT"
echo "============================================"
echo ""
echo "Please add these files to the 'Keyboard Copilot' target in Xcode:"
echo ""
echo "Models:"
echo "  • App/Sources/Models/AppState.swift"
echo ""
echo "Components:"
echo "  • App/Sources/Components/PrimaryButton.swift"
echo ""
echo "Managers:"
echo "  • App/Sources/Managers/HapticFeedbackManager.swift"
echo "  • App/Sources/Managers/KeyboardDetectionHelper.swift"
echo "  • App/Sources/Managers/AppIconManager.swift"
echo ""
echo "Views - Onboarding:"
echo "  • App/Sources/Views/Onboarding/WelcomeView.swift"
echo "  • App/Sources/Views/Onboarding/LogoSelectionView.swift"
echo "  • App/Sources/Views/Onboarding/KeyboardSetupView.swift"
echo "  • App/Sources/Views/Onboarding/KeyboardTestView.swift"
echo "  • App/Sources/Views/Onboarding/OnboardingCoordinator.swift"
echo ""
echo "Views - Home:"
echo "  • App/Sources/Views/Home/HomeView.swift"
echo "  • App/Sources/Views/Home/SettingsRow.swift"
echo ""
echo "============================================"
echo "HOW TO ADD THEM:"
echo "============================================"
echo "1. In Xcode, right-click on 'App' in the Project Navigator"
echo "2. Select 'Add Files to Keyboard Copilot...'"
echo "3. Navigate to App/Sources/"
echo "4. Select the Models, Components, Managers, and Views folders"
echo "5. Make sure 'Copy items if needed' is UNCHECKED"
echo "6. Make sure 'Create groups' is selected"
echo "7. Make sure 'Keyboard Copilot' target is CHECKED"
echo "8. Click Add"
echo "============================================"
